name: dictionary
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.0.0
  get: ^4.6.5
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  either_dart: ^1.0.0
  intl: ^0.19.0
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  lottie: ^3.1.2
  cupertino_icons: ^1.0.6
  gherkin: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  flutter_gherkin: ^3.0.0-rc.17
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dictionary_logo.png"
  min_sdk_android: 21



flutter:
  uses-material-design: true

  assets:
    - assets/words_dictionary.json
    - assets/test_words_dictionary.json
    - assets/words.json
    - assets/empty_state.json
    - assets/empty_state.json
    - assets/dictionary_logo.png
